[metadata]
name = knnopt
version = 0.1.0
description = A modular Python toolkit for benchmarking and visualizing optimal K values in KNN classification.
long_description = file: README.md
long_description_content_type = text/markdown
author = Guy Kaptue
author_email = guykaptue24@gmail.com
license = MIT
url = https://github.com/GuyKaptue/knnopt
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
include_package_data = True

[options.extras_require]
dev =
    pytest>=7.0
    black>=22.0
    flake8>=4.0
    mypy>=0.900
    jupyter>=1.0.0

[flake8]
max-line-length = 88
exclude = .git,__pycache__,build,dist

[mypy]
ignore_missing_imports = True

[tool:pytest]
addopts = --strict-markers
testpaths = tests
